Install additional fonts
networksforchange/meteord pull request #4
Opened 2023-01-13 18:34 UTC by KeinerM

### This PR is for

- [ ] Cosmetic Changes
- [ ] Customer Issue
- [ ] Bug Fix
- [X] Feature or Enhancement
- [ ] Refactoring
- [ ] Documentation, Tests, or DX (Developer Experience; config settings etc.)

### Description & Issue/Ticket References

Github: https://github.com/networksforchange/nfc-keela/issues/10895
Linear:  [🔎 [Investigation Request] - Chinese Name and Address not coming to receipt](https://linear.app/keela/issue/WEB-3062/🔎-[investigation-request]-chinese-name-and-address-not-coming-to)

**_What does this PR do?_**
- Installs additional fonts that support South Asian languages like Japanese, Chinese, Korean, Thai, Bengali, Nepali, and others. 

The library `wkhtmltopdf` uses the fonts installed in the system to render the PDFs.

2023-01-13 18:56 UTC, xolott commented on base/scripts/lib/install_fonts.sh
> +    fonts-noto-cjk
Just an empty line missing at the EOF.

```suggestion
    fonts-noto-cjk

```

2023-01-13 18:57 UTC, xolott requested changes
Wrong option. I meant to request changes.

2023-01-23 16:36 UTC, xolott approved these changes

2023-01-25 10:02 UTC, WayneUong commented
@KeinerM I merged it directly to master, it's testable on dev now.
https://github.com/networksforchange/meteord/pull/5/files

2023-01-25 10:02 UTC, closed without merging